language: scala
sudo: true
script:
  - sbt test
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
before_script:
  - sudo apt-get install libaio1
  - sudo /etc/init.d/mysql stop
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE gitbucket;" -U postgres
